


INSERT INTO treatments (name, description, standard_price) VALUES
                                                               ('Tooth Filling', 'Composite resin filling for cavities or minor cracks.', 30000.00),
                                                               ('Root Canal Treatment', 'Endodontic procedure to remove infected pulp.', 80000.00),
                                                               ('Tooth Extraction', 'Simple or surgical removal of damaged teeth.', 20000.00),
                                                               ('Scaling & Polishing', 'Removal of tartar and plaque from teeth.', 15000.00),
                                                               ('Dental X-Ray', 'Diagnostic imaging for internal tooth and bone issues.', 10000.00),
                                                               ('Braces (Consultation)', 'Initial consultation for orthodontic treatment.', 5000.00),
                                                               ('Teeth Whitening', 'Bleaching treatment for stained or discolored teeth.', 45000.00),
                                                               ('Crown Placement', 'Restorative cap to cover a damaged tooth.', 100000.00),
                                                               ('Partial Denture', 'Removable partial denture for missing teeth.', 70000.00),
                                                               ('Full Denture', 'Complete denture replacement for all teeth.', 120000.00),
                                                               ('Dental Implant', 'Artificial tooth root for permanent tooth replacement.', 200000.00),
                                                               ('Gum Surgery', 'Treatment for advanced periodontal disease.', 95000.00),
                                                               ('Orthodontic Braces', 'Appliances used to straighten teeth.', 300000.00),
                                                               ('Fluoride Treatment', 'Strengthens enamel and prevents decay.', 8000.00),
                                                               ('Sealants', 'Protective coating for molars to prevent decay.', 12000.00),
                                                               ('Night Guard', 'Custom mouthguard for teeth grinding.', 40000.00),
                                                               ('Retainers', 'Used after braces to retain tooth position.', 25000.00),
                                                               ('Wisdom Tooth Removal', 'Surgical removal of impacted wisdom tooth.', 60000.00),
                                                               ('Bone Grafting', 'Procedure to rebuild jaw bone for implants.', 150000.00),
                                                               ('Sinus Lift', 'Surgical procedure for upper jaw implant preparation.', 130000.00),
                                                               ('Orthodontic Adjustment', 'Regular tightening of braces.', 10000.00),
                                                               ('Laser Whitening', 'Laser-assisted teeth whitening treatment.', 60000.00),
                                                               ('Tooth Jewelry', 'Cosmetic dental accessory.', 15000.00),
                                                               ('Invisalign', 'Clear aligners for teeth straightening.', 350000.00),
                                                               ('Emergency Pain Relief', 'Immediate treatment for dental pain.', 18000.00),
                                                               ('Cavity Prevention Kit', 'Includes sealants, fluoride, and cleaning.', 30000.00),
                                                               ('Pediatric Cleaning', 'Gentle cleaning for children.', 10000.00),
                                                               ('Pediatric Filling', 'Tooth-colored fillings for children.', 15000.00),
                                                               ('Mouth Ulcer Treatment', 'Relief for painful mouth ulcers.', 7000.00),
                                                               ('Bleeding Gums Treatment', 'Deep cleaning and medication.', 22000.00),
                                                               ('Oral Cancer Screening', 'Visual and physical exam for signs of cancer.', 25000.00),
                                                               ('Temporary Crown', 'Short-term tooth cap placement.', 15000.00),
                                                               ('Permanent Bridge', 'Fixed replacement for missing teeth.', 90000.00),
                                                               ('Temporary Bridge', 'Short-term replacement bridge.', 40000.00),
                                                               ('Tooth Recontouring', 'Cosmetic reshaping of teeth.', 12000.00),
                                                               ('Tooth Desensitization', 'Treatment for sensitive teeth.', 10000.00),
                                                               ('Orthodontic Retainer Check', 'Follow-up exam for retainers.', 5000.00),
                                                               ('TMJ Treatment', 'Therapy for jaw joint disorders.', 35000.00),
                                                               ('Teeth Cleaning (Deep)', 'Scaling below gumline for gum disease.', 25000.00),
                                                               ('Oral Prophylaxis', 'Professional cleaning of teeth.', 20000.00),
                                                               ('Tooth Bonding', 'Cosmetic application of resin on teeth.', 28000.00),
                                                               ('Dental Veneers', 'Thin covers for discolored or broken teeth.', 85000.00),
                                                               ('Tooth Gap Filling', 'Cosmetic closure of gaps between teeth.', 25000.00),
                                                               ('Post & Core', 'Reinforcement of severely damaged tooth.', 30000.00),
                                                               ('Tooth Re-implantation', 'Reattaching knocked-out tooth.', 45000.00),
                                                               ('Tooth Bleaching (Home Kit)', 'Take-home whitening kit.', 38000.00),
                                                               ('Pre-Braces X-ray', 'X-ray before orthodontic treatment.', 8000.00),
                                                               ('Panoramic X-ray', 'Full mouth X-ray.', 15000.00),
                                                               ('Intraoral Camera Exam', 'Digital image exam using small camera.', 12000.00);

INSERT INTO dentists (name, specialization, phone, email) VALUES
                                                              ('Dr. Aung Myat Thu', 'General Dentistry', '09111111111', 'aungmyatthu@gmail.com'),
                                                              ('Dr. Su Mon Kyaing', 'Orthodontics', '09222222222', 'sumonkyaing@gmail.com'),
                                                              ('Dr. Min Htet Oo', 'Endodontics', '09333333333', 'minhtetoo@gmail.com'),
                                                              ('Dr. Kyaw Zin Latt', 'Pediatric Dentistry', '09444444444', 'kyawzinlatt@gmail.com'),
                                                              ('Dr. Khin Hnin Wai', 'Prosthodontics', '09555555555', 'khinhninwai@gmail.com'),
                                                              ('Dr. Ko Ko Naing', 'Periodontics', '09666666666', 'kokonaing@gmail.com'),
                                                              ('Dr. Phyu Phyu Win', 'Oral Surgery', '09777777777', 'phyuphyuwin@gmail.com'),
                                                              ('Dr. Thura Aung', 'Cosmetic Dentistry', '09888888888', 'thuraaung@gmail.com'),
                                                              ('Dr. Nilar Soe', 'Implantology', '09999999999', 'nilarsoe@gmail.com'),
                                                              ('Dr. Moe Moe Myint', 'Orthodontics', '09123456789', 'moemoemyint@gmail.com'),
                                                              ('Dr. Tun Tun Oo', 'General Dentistry', '09234567891', 'tuntunoo@gmail.com'),
                                                              ('Dr. Hla Hla Win', 'Periodontics', '09345678912', 'hlahlawin@gmail.com'),
                                                              ('Dr. Zaw Lin', 'Endodontics', '09456789123', 'zawlin@gmail.com'),
                                                              ('Dr. Aye Chan', 'Prosthodontics', '09567891234', 'ayechan@gmail.com'),
                                                              ('Dr. Nyo Nyo Win', 'General Dentistry', '09678912345', 'nyonyowin@gmail.com'),
                                                              ('Dr. Kyaw Kyaw', 'Oral Surgery', '09789123456', 'kyawkyaw@gmail.com'),
                                                              ('Dr. Ei Mon Kyaing', 'Cosmetic Dentistry', '09891234567', 'eimonkyaing@gmail.com'),
                                                              ('Dr. Myo Min Tun', 'Orthodontics', '09912345678', 'myomintun@gmail.com'),
                                                              ('Dr. Htet Htet Aung', 'Pediatric Dentistry', '09123456700', 'htethtetaung@gmail.com'),
                                                              ('Dr. Win Win Soe', 'Periodontics', '09234567001', 'winwinsoe@gmail.com'),
                                                              ('Dr. Nay Aung', 'Implantology', '09345670012', 'nayaung@gmail.com'),
                                                              ('Dr. San San Myint', 'General Dentistry', '09456700123', 'sansanmyint@gmail.com'),
                                                              ('Dr. Thiri Htun', 'Endodontics', '09567001234', 'thirihtun@gmail.com'),
                                                              ('Dr. Aung Naing Lin', 'Prosthodontics', '09670012345', 'aungnainglin@gmail.com'),
                                                              ('Dr. Khin Mar Soe', 'Cosmetic Dentistry', '09700123456', 'khinmarsoe@gmail.com'),
                                                              ('Dr. Soe Soe Lwin', 'Orthodontics', '09801234567', 'soesoelwin@gmail.com'),
                                                              ('Dr. Linn Htet', 'General Dentistry', '09912345000', 'linnhtet@gmail.com'),
                                                              ('Dr. Cho Cho', 'Pediatric Dentistry', '09111111222', 'chocho@gmail.com'),
                                                              ('Dr. Nyein Chan', 'Periodontics', '09222222333', 'nyeinchan@gmail.com'),
                                                              ('Dr. Zaw Moe', 'Oral Surgery', '09333333444', 'zawmoe@gmail.com'),
                                                              ('Dr. Mya Mya Tun', 'Implantology', '09444444555', 'myamyatun@gmail.com'),
                                                              ('Dr. Nay Thway', 'Orthodontics', '09555555666', 'naythway@gmail.com'),
                                                              ('Dr. Mya Thet', 'General Dentistry', '09666666777', 'myathet@gmail.com'),
                                                              ('Dr. Khin Khin Htwe', 'Cosmetic Dentistry', '09777777888', 'khinkhinhtwe@gmail.com'),
                                                              ('Dr. Kaung Htet', 'Endodontics', '09888888999', 'kaunghtet@gmail.com'),
                                                              ('Dr. Win Aung', 'Prosthodontics', '09999999000', 'winaung@gmail.com'),
                                                              ('Dr. Moe Moe Aung', 'Periodontics', '09121212121', 'moemoeaung@gmail.com'),
                                                              ('Dr. Ye Min', 'Oral Surgery', '09232323232', 'yemin@gmail.com'),
                                                              ('Dr. Hnin Ei Mon', 'Orthodontics', '09343434343', 'hnineimon@gmail.com'),
                                                              ('Dr. Ko Ko Hlaing', 'Pediatric Dentistry', '09454545454', 'kokohlaing@gmail.com'),
                                                              ('Dr. Wai Wai', 'Cosmetic Dentistry', '09565656565', 'waiwai@gmail.com'),
                                                              ('Dr. Phyo Phyo', 'General Dentistry', '09676767676', 'phyophyo@gmail.com'),
                                                              ('Dr. Thet Naing', 'Implantology', '09787878787', 'thetnaing@gmail.com'),
                                                              ('Dr. Than Than Aye', 'Orthodontics', '09898989898', 'thanthanaye@gmail.com'),
                                                              ('Dr. Khin Khin Lay', 'Endodontics', '09909090909', 'khinkhinlay@gmail.com'),
                                                              ('Dr. Thura Lin', 'Prosthodontics', '09191919191', 'thuralin@gmail.com'),
                                                              ('Dr. Aye Mya', 'Oral Surgery', '09202020202', 'ayemya@gmail.com'),
                                                              ('Dr. Zaw Win', 'Pediatric Dentistry', '09303030303', 'zawwin@gmail.com'),
                                                              ('Dr. Ei Ei Phyo', 'General Dentistry', '09404040404', 'eieiphyo@gmail.com'),
                                                              ('Dr. Hlaing Bwar', 'Orthodontics', '09505050505', 'hlaingbwar@gmail.com');


